name: on_site_crews
description: "A new Flutter project."

# To publish the package to pub.dev, remove the 'none' and fill out the details if needed.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# App version
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: '>=3.4.4 <4.0.0'

# Project dependencies
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6


  # Geolocation package for Flutter
  geolocator: ^13.0.1
  geolocator_web: ^4.1.1 # or the latest version

  # Fluent UI system icons
  fluentui_system_icons: ^1.1.2


  # Audio player package
  just_audio: ^0.9.32 # or the latest version
  just_audio_web: ^0.4.8 # or the latest version

  # State management package
  provider: ^6.0.0


  # Shared preferences for storing simple data
  shared_preferences: ^2.0.15
  shared_preferences_web: ^2.0.15 # or the latest version

  # Google Maps integration
  google_maps_flutter: ^2.2.0
  google_maps_flutter_web: ^0.4.0 # or the latest version

  # Web support for image picker
  image_picker_web: ^4.0.0

  # Google Fonts for custom typography google_fonts and google fonts web removed
  #google_fonts: ^6.2.1
  #google_fonts_web: ^6.2.1 # or the latest version

  # Smooth page indicators for swiping removed
  smooth_page_indicator: ^1.2.0+3

  # Image picker support
  image_picker: ^0.8.5+3 # or the latest version

# Dev dependencies for testing and linting
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter settings
flutter:
  uses-material-design: true

  # Assets used in the project
  assets:
    - assets/images/
    - assets/sounds/